<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\TimeUnit;

/* @var $this yii\web\View */
/* @var $model app\models\Period */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="period-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="row">

        <div class="col-md-3">
            <?= $form->field($model, 'name',['enableAjaxValidation' => true])->textInput(['maxlength' => true, 'id' => 'name', 'placeholder' => 'Type period name here...']) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'code',['enableAjaxValidation' => true])->textInput(['maxlength' => true, 'id' => 'code', 'placeholder' => 'Will be autogenerated', 'readonly' => true]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'time_unit_id')->dropDownList(TimeUnit::getUnits(), ['prompt' => 'Select...']) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'weight')->textInput(['type' => 'number', 'min' => 1]) ?>
        </div>
    </div>

    <div class="form-group">
        <?= $form->field($model, 'is_active')->checkbox() ?>
    </div>




    <?php //$form->field($model, 'created_at')->textInput() ?>

    <?php //$form->field($model, 'created_by')->textInput() ?>

    <?php //$form->field($model, 'updated_at')->textInput() ?>

    <?php //$form->field($model, 'updated_by')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>



    <script>
        function generateCode() {
            const name = $('#name').val();
            const code = `PERIOD_${name}`.toUpperCase();
            $('#code').val(code);
        }
        $(document).ready(() => {

            if (parseInt("<?= $model->isNewRecord ?>") !== 1) {
                generateCode();
            }

            $('#name').keyup(() => {
                generateCode();
            });
        });
    </script>

</div>
